services:
  - type: web
    name: brain-tumor-backend
    env: python
    runtime: python-3.10.13
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT

    
